config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "work_histories#index"

  resources :work_histories, except: [ :show, :destroy ]  

  namespace :work_histories do
    get :now
    post :check_now
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/hours_controllable.rb
# frozen_string_literal: true

# app/models/concerns/hours_controllable.rb
module HoursControllable
  extend ActiveSupport::Concern

  # Call default_hours_config method if ends_at is present
  def update_default_hours
    default_hours_config if ends_at.present?
  end

  # Converts a worked_hours (integer) to a Time value
  def worked_hours_to_time
    (Time.new.beginning_of_day + worked_hours.hours).strftime('%H:%M')
  end

  # validate if work_history already exists
  def work_history_date
    work_history = WorkHistory.find_by(user_id: user_id, starts_at: starts_at.beginning_of_day..starts_at.end_of_day)

    return if work_history.blank?

    errors.add(:base, 'Não é permitido exitir dois ponto no mesmo dia') if work_history.ends_at.present?
  end

  private

  # set hours default config
  def default_hours_config
    lunch_hours_config

    total_hours = (ends_at - starts_at) / 1.hour

    if lunch_starts.nil? && lunch_ends.nil?
      self.worked_hours = total_hours - 1.0
    else
      lunch_time = (lunch_ends - lunch_starts) / 1.hour
      self.worked_hours = total_hours - lunch_time
    end
  end

  # set lunch hours config
  def lunch_hours_config
    self.lunch_starts = starts_at + 4.hours if lunch_starts.nil? && ends_at >= starts_at + 9.hours

    self.lunch_ends = lunch_starts + 1.hour if lunch_ends.nil? && lunch_starts.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
end

app/models/work_history.rb
# frozen_string_literal: true

# app/models/work_history.rb
class WorkHistory < ApplicationRecord
  include HoursControllable
  belongs_to :user

  before_save :update_default_hours

  validate :work_history_date, on: :create
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# appp/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/concerns/work_history_now.rb
# frozen_string_literal: true

# app/controllers/concerns/work_history_now.rb
module WorkHistoryNow
  extend ActiveSupport::Concern

  # Set new work history with current time
  def set_work_history_now
    work_history_config
  end

  private

  def work_history_config
    @work_history = WorkHistory.find_by(user_id: current_user.id, starts_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    if @work_history.blank?
      @work_history = WorkHistory.new
      @work_history.user_id = current_user.id
    elsif @work_history.ends_at.present?
      @work_history = nil
    end
  end
end

app/controllers/work_histories_controller.rb
# frozen_string_literal: true

# app/controllers/work_histories_controller.rb
class WorkHistoriesController < ApplicationController
  include WorkHistoryNow

  before_action :set_work_history, only: %i[edit update]
  before_action :set_work_history_now, only: %i[now check_now]

  # GET /work_histories
  def index
    @work_histories = WorkHistory.where(user_id: current_user.id)
  end

  # GET /work_histories/new
  def new
    @work_history = WorkHistory.new
  end

  # POST /work_histories
  def create
    @work_history = WorkHistory.new(work_history_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @work_history.save
        format.html { redirect_to work_histories_path, notice: 'Ponto criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  # GET /work_histories/:id/edit
  def edit; end

  # PUT /work_histories/:id
  def update
    respond_to do |format|
      if @work_history.update(work_history_params)
        format.html { redirect_to work_histories_path, notice: 'Ponto editado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  # GET /work_histories/now
  def now; end

  # POST /work_histories/check_now
  def check_now
    respond_to do |format|
      if @work_history.update(work_history_params)
        format.html { redirect_to work_histories_path, notice: 'Ponto salvo sucesso.' }
      else
        format.html { render :now }
      end
    end
  end

  private

  # Find work history and set it to share common setup
  def set_work_history
    @work_history = WorkHistory.find_by(id: params[:id], user_id: current_user)
  end

  # Only allow a list of trusted parameters through.
  def work_history_params
    params.require(:work_history).permit(:starts_at, :ends_at, :lunch_starts, :lunch_ends)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Time To Work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class='row'>
        <% if notice.present? %>
          <div class="notification is-info is-light">
            <p id="notice"><%= notice %></p>
          </div>
        <% end %>
        <%= yield %>
      </div>  
    </div>  
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        Time To Work
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to work_histories_now_path, class: 'button is-success' do %>
                <span class="icon">
                  <i class="fas fa-plus-circle"></i>
                </span>
                <span>Bater ponto agora</span>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button is-light'  %>
            <% else %>
              <a class="button is-primary" href='/users/sign_up'>
                <strong>Sign up</strong>
              </a>
              <a class="button is-light" href='/users/sign_in'>
                Login 
              </a>
            <% end %>  
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/work_histories/_form.html.erb
<%= form_with(model: work_history, local: true) do |form| %>
  <% if work_history.errors.any? %>
    <div id="error_explanation" class="notification is-danger is-light">
      <h2><%= pluralize(work_history.errors.count, "error") %> Erros encontrados:</h2>

      <ul>
        <% work_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="label">Entrada: </label>
    <p class="control">
      <%= form.datetime_field :starts_at, class: "input" %>
    </p>
  </div>

  <div class="field">
    <label class="label">Início almoço: </label>
    <p class="control">
      <%= form.datetime_field :lunch_starts, class: "input" %>
    </p>
  </div>

  <div class="field">
    <label class="label">Fim almoço: </label>
    <p class="control">
      <%= form.datetime_field :lunch_ends, class: "input" %>
    </p>
  </div>

  <div class="field">
    <label class="label">Saída: </label>
    <p class="control">
      <%= form.datetime_field :ends_at, class: "input" %>
    </p>
  </div>

  <br/>
  <div class="field">
    <p class="control center">
      <%= form.submit nil, class: 'button is-fullwidth is-rounded is-primary' %>
    </p>
  </div>
<% end %>

app/views/work_histories/edit.html.erb
<section class="section">
    <div class="container column is-half">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered">Editar Ponto</h1>
    </div>

    <div class="container column is-half">
        <%= render 'form', work_history: @work_history %>
    </div>

    <div class="container column is-one-fifth center">
        <%= link_to 'Voltar', work_histories_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
    </div>
</section>

app/views/work_histories/index.html.erb
<section class="section">
    <div class="container column is-half is-mobile">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered"> <i class="far fa-calendar-check"></i> Histórico de pontos</h1>
    </div>    

    <div class="column is-mobile">
        <div class="column is-10 is-offset-2">
            <div class="column is-one-fifth">
                <%= link_to 'Novo Ponto', new_work_history_path, class: "button is-fullwidth is-rounded is-outlined is-black" %>
            </div>
       

            <br>

            <div class="table-container">
                <table class="table is-striped">
                    <thead>
                        <tr>
                            <th>Entrada</th>
                            <th>Inicio almoço</th>
                            <th>Fim almoço</th>
                            <th>Saída</th> 
                            <th>Saldo Hora</th>
                            <th colspan="1"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% total = 0.0%>
                        <% @work_histories.each do |work_history| %>
                            <tr>
                                <td><%= work_history.starts_at.strftime("%d/%m/%y -  %H:%M") %></td>
                                <td><%= work_history.lunch_starts.strftime("%d/%m/%y -  %H:%M") rescue '-' %></td>
                                <td><%= work_history.lunch_ends.strftime("%d/%m/%y -  %H:%M") rescue '-'%></td>
                                <td><%= work_history.ends_at.strftime("%d/%m/%y - %H:%M") rescue '-'%></td> 
                                <td><%= work_history.worked_hours_to_time rescue '-'%></td>
                                <td><%= link_to 'Editar', edit_work_history_path(work_history), class: "button is-fullwidth is-rounded is-outlined is-info" %></td>
                            </tr>
                            <% worked_hours = work_history.worked_hours.to_f rescue 0.0%>
                            <% total += worked_hours %>
                        <% end %>
                    </tbody>
                </table>
            </div>

            <div class="container column is-half center">
                    <p class="control center">
                        <% hours = total.divmod 1 # function in Ruby returns integer division value and the remainder. %>
                        Total: <%= hours[0] %> horas e <%= (Time.new.beginning_of_day+hours[1].hours).strftime('%M')%> minutos
                    </p>
            </div>
         </div>
    </div>
</section>

app/views/work_histories/new.html.erb
<section class="section">
    <div class="container column is-half">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered">Novo Ponto</h1>
    </div>
    
    <div class="container column is-half">
        <%= render 'form', work_history: @work_history %>
    </div>

    <div class="container column is-one-fifth center">
        <%= link_to 'Back', work_histories_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
    </div>
</section>

app/views/work_histories/now.html.erb
<section class="section">
    <div class="container column is-half">
        <h1 class="is-size-3 is-size-4-mobile has-text-centered">Bater Ponto Agora</h1>
    </div>
    <% if @work_history.nil? %>
        <div class="notification is-danger is-light">
            <p class="control center">
                Não é permitido bater o ponto duas vezes ao dia
            </p>
        </div>
    <% else %>
        <div class="container column is-half">
            
            <% if @work_history.starts_at.blank? %>
                <%= form_tag(work_histories_check_now_path) do %>
                    <%= hidden_field_tag 'work_history[starts_at]', Time.now %>
                    <div class="container column is-half center">
                        <p class="control center">
                            <%= submit_tag 'Entrada', class: 'button is-fullwidth is-rounded is-info' %>
                        </p>
                    </div>
                <% end %>
            <% else %>
                <%= form_tag(work_histories_check_now_path) do %>
                    <% if @work_history.lunch_starts.blank? %>
                        <%= hidden_field_tag 'work_history[lunch_starts]', Time.now %>
                        <div class="container column is-half center">
                            <p class="control center">
                                <%= submit_tag 'Almoço', class: 'button is-fullwidth is-rounded is-primary' %>
                            </p>
                        </div>
                    <% elsif  @work_history.lunch_ends.blank? %>
                        <%= hidden_field_tag 'work_history[lunch_ends]', Time.now %>
                        <div class="container column is-half center">
                            <p class="control center">
                                <%= submit_tag 'Fim Almoço', class: 'button is-fullwidth is-rounded is-warning' %>
                            </p>
                        </div>
                    <%end %>
                <% end %>
                <%= form_tag(work_histories_check_now_path) do %>
                    <%= hidden_field_tag 'work_history[ends_at]', Time.now %>
                    <div class="container column is-half center">
                        <p class="control center">
                            <%= submit_tag 'Saida', class: 'button is-fullwidth is-rounded is-danger' %>
                        </p>
                    </div>
                <% end %>            
            <% end %>            
        </div>
    <%end%>
    <div class="container column is-one-fifth center">
        <%= link_to 'Back', work_histories_path, class: "button is-fullwidth is-rounded is-outlined is-link" %>
    </div>
</section>